baseurl = "/"
title = "SODA Foundation Blog"
theme = "hugo-nederburg-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = "opensds"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-138679091-1"
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination

[privacy]
  # Google Analytics privacy settings - https://gohugo.io/about/hugo-and-gdpr/index.html#googleanalytics
  [privacy.googleAnalytics]
    # set to true to disable service
    disable = false
    # set to true to meet General Data Protection Regulation (GDPR)
    anonymizeIP = false
    respectDoNotTrack = false
    useSessionStorage = false

[params]
  # Site Logo
  logo = "/img/SODA_logo.png"
  # Unmark to use post folder for images. Default is static folder.
  #usepostimgfolder = true
  slogan = "The official blog for the SODA Foundation project."
  description = "An open source community working under The Linux Foundation to address storage integration challenges in scale-out cloud native environments. Its vision is to connect siloed data solutions to build a self governed and intelligent data platform." # meta description
  # You need to set author to have an author bio. If you have a writer in the markdown file it will override this.
  author = "SODA Foundation"
  authorLink = "https://sodafoundation.io/"
  bio = [
    "The Open Autonomous Data Platform"
  ]
  copyright = [
    "&copy; 2022 SODA Foundation",
    "Nederburg Hugo Theme by [Appernetic](https://appernetic.io)."
  ]


  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below (it is also used in Gravatar for the bio).
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "lfsodafoundation@gmail.com"

  # Nav links in the side bar
  [[menu.main]]
  name = "Blog Home"
  url = "/"
  weight = 1

  # [[menu.main]]
  # name = "About"
  # url = "about/"
  # weight = 2

  [[menu.main]]
   name = "Categories"
   url = "categories/"
   weight = 2

  # [[menu.main]]
  # name = "Get in touch"
  # url = "contact/"
  # weight = 3

  [[menu.main]]
   name = "Back to SODA Foundation website"
   url = "https://sodafoundation.io"
   weight = 3

# this will also be in author bio if there is no writer.
  [params.social]
  # facebook      = "https://www.facebook.com/lfopensds/"
  # googleplus    = "full profile url in googleplus"
  email         = "lfsodafoundation@gmail.com"
  twitter       = "https://twitter.com/sodafoundation"
  linkedin      = "https://www.linkedin.com/company/sodafoundation/"
  # stackoverflow = "full profile url in stackoverflow"
  # instagram     = "full profile url in instagram"
  github        = "https://github.com/sodafoundation"
  # pinterest     = "full profile url in pinterest"
  rss           = true

# Add a writer, then use it in the markdown front matter like this: writer = "Lukas Herman"
  [params.writers]
    [params.writers."Sean McGinnis"]
    link = ""
    email = "sean.mcginnis@gmail.com"
    bio = [
      "OpenSDS community and release manager"
    ]
    # facebook      = "full lukas profile url in facebook"
    # googleplus    = "full profile url in googleplus"
    twitter       = "https://twitter.com/SeanTMcGinnis"
    # linkedin      = "full profile url in linkedin"
    # stackoverflow = "full profile url in stackoverflow"
    # instagram     = "full profile url in instagram"
    # github        = "full profile url in github"
    # pinterest     = "full profile url in pinterest"

    [params.writers."Xing Yang"]
    link = ""
    email = "xingyang105@gmail.com"
    bio = [
      "Lead Architect of OpenSDS"
    ]
    # facebook      = "full GÃ¶ran profile url in facebook"
    # googleplus    = "full profile url in googleplus"
    twitter       = "https://twitter.com/2000Xyang"
    # linkedin      = "full profile url in linkedin"
    # stackoverflow = "full profile url in stackoverflow"
    # instagram     = "full profile url in instagram"
    # github        = "full profile url in github"
    # pinterest     = "full profile url in pinterest"

    [params.writers."Sanil Kumar D."]
    link = ""
    email = "skdsanil@gmail.com"
    bio = [
      "Chief Architect of OpenSDS"
    ]
    # facebook      = "full lukas profile url in facebook"
    # googleplus    = "full profile url in googleplus"
    twitter       = "https://twitter.com/sanilkumard"
    # linkedin      = "full url"
    # stackoverflow = "full profile url in stackoverflow"
    # instagram     = "full url"
    # github        = "full url"
    # pinterest     = "full profile url in pinterest"

    [params.writers."Pravin Ranjan"]
    link = ""
    email = "pravinranjan10@gmail.com"
    bio = [
      "Maintainer, SODA Foundation"
    ]
    facebook      = "https://www.facebook.com/pravni.jhunna"
    # googleplus    = "full profile url in googleplus"
    twitter       = "https://twitter.com/10PravinRanjan"
    linkedin      = "https://www.linkedin.com/in/pravinranjan10/"
    stackoverflow = "https://stackoverflow.com/users/4519003/pravin"
    # instagram     = "full url"
    github        = "https://github.com/PravinRanjan10"
    # pinterest     = "full profile url in pinterest"

    [params.writers."Joseph Vazhappilly"]
    link = ""
    email = "josephvp@gmail.com"
    bio = [
      "Maintainer, SODA Foundation"
    ]
    # facebook      = "full lukas profile url in facebook"
    # googleplus    = "full profile url in googleplus"
    # twitter       = "https://twitter.com/sanilkumard"
    # linkedin      = "full url"
    # stackoverflow = "full profile url in stackoverflow"
    # instagram     = "full url"
    github        = "https://github.com/joseph-v/"
    # pinterest     = "full profile url in pinterest"
